#!/usr/bin/env bash
# A Bash script that accepts one argument.
# The script run the whoami command under the user passed as an argument.
# make sure to try your script by passing different users.

sudo -u "$1" whoami
