#!/usr/bin/env bash
# Fixes a web server to run Nginx as the nginx user listening on port 8080.
# Fix this container so that Nginx is running as the nginx user.
# Requirements:
#   -nginx must be running as nginx usernginx must be listening on all
#    active IPs on port 8080.
#   -You cannot use apt-get remove.
#   -Write a Bash script that configures the container to fit the above
#    requirements.

# Nginx running as the nginx user.
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# replace port 80 with 8080 in the sites-available config.
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# Set the permissions to read and write to the config file
chmod 644 /etc/nginx/nginx.conf

# kill the APACHE2 process if it is running to avoid interfere with nginx
pkill apache2

# Start the nginx service with the new nginx user
sudo -u nginx service nginx start
